# Generated by Django 5.1.6 on 2025-02-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesmodel',
            name='bandligi',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablesmodel',
            name='qr_code',
            field=models.ImageField(default=1, upload_to='QR_Code/'),
            preserve_default=False,
        ),
    ]
