# Generated by Django 5.1.6 on 2025-02-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.BigIntegerField(unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status_Choice', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('bandligi', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='QR_Code/')),
                ('xona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roommodels')),
            ],
        ),
        migrations.DeleteModel(
            name='TablesModels',
        ),
    ]
