# Generated by Django 5.1.6 on 2025-02-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tablesmodel_bandligi_tablesmodel_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesmodel',
            name='raqam',
            field=models.BigIntegerField(unique=True),
        ),
    ]
