# Generated by Django 5.1.6 on 2025-02-17 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_categoryfood_commentmodel_commentreply_foodpost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='video',
            field=models.FileField(upload_to='products_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])]),
        ),
    ]
